# Generated by Django 3.2.15 on 2022-09-29 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20220915_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='profile_photo',
            field=models.ImageField(null=True, upload_to='static/images/users/'),
        ),
    ]
